### ISSUE TITLE
Profile link button doesn't work if you're coming from another page.

### ISSUE THREAD

**Issue by JeffLuong** [JeffLuong/Neighbor_Nation#25]
I noticed that if you're on the 'suggestions' page, and you click the profile link, it doesn't take you anywhere. @DerekJacobi any ideas as to why? May be the if statement we placed inside the html.erb....

**Comment by DerekJacobi** [comment]
@JeffLuong its hitting the user show route which takes the user id parameter from the url, but when the suggestion box is clicked, the route is /suggestions. Ill fix it show it users the current user id for the route

**Comment by JeffLuong** [comment]
Just gonna comment that this is fixed. Closing this issue.
